# TRANSFORM

if duration is negative, remove row? (merged_df)

In [1]:
import pandas as pd
import datetime as dt

In [2]:
#Import Found csv
found_df = pd.read_csv("AAC_Found.csv")

#Select rows where Type= "Dog"
found_df = found_df.loc[found_df['Type'] == 'Dog']

#Select columns ('Animal ID', 'Found Location', 'At AAC', 'Intake Date', 'Looks Like', 'Color','Sex','Age','Image Link')
found_df = found_df[['Animal ID', 
                     'Found Location', 
                     'At AAC', 
                     'Intake Date',
                     'Looks Like', 
                     'Color',
                     'Sex',
                     'Age',
                     'Image Link']]

#Rename looks like column
found_df.rename(columns = {'Looks Like': 'Breed(unconfirmed)'}, inplace = True)

#Split Sex column into gender and found sex
#split value of Sex upon intake column
found_sex_split = found_df['Sex'].str.split(" ", n = 1, expand = True) 
  
# making separate intake sex column from new data frame 
found_df["Found_Sex"]= found_sex_split[0] 

# making separate gender column from new data frame 
found_df["Gender"]= found_sex_split[1] 
  
# Dropping old Sex upon intake column
found_df.drop(columns =['Sex'], inplace = True) 

#Split Found Location column into address and coordinates
#split value of found location column
found_loc_split = found_df['Found Location'].str.split("(", n = 1, expand = True) 
  
# making separate address column from new data frame 
address = found_loc_split[0].str.rstrip()

#Extract zip code (last 5 characters of address)
found_df["Zip_code"] = address.str[-5:]

#split Lat/Long on ","
found_coord_split = found_loc_split[1].str.split(",", n = 1, expand = True) 
# making separate coordinate columns from new data frame 
found_df["Latitude"] = found_coord_split[0] 
found_df["Longitude"] = found_coord_split[1].str.replace(')', '') 


found_df.head()

#found_df.count()

,Animal ID,Found Location,At AAC,Intake Date,Breed(unconfirmed),Color,Age,Image Link,Found_Sex,Gender,Zip_code,Latitude,Longitude
2,A808186,"BAHAN DRIVE 78617\n(30.157123, -97.611102)",Yes (come to the shelter),11/05/2019,English Bulldog,Brown/White,1 year,http://www.petharbor.com/pet.asp?uaid=ASTN.A80...,Intact,Female,78617,30.157123,-97.611102
3,A807919,"6001 OLEANDAR TRAIL\nAUSTIN 78735\n(30.251613,...",Yes (come to the shelter),11/01/2019,Chihuahua Shorthair,White,5 years,http://www.petharbor.com/pet.asp?uaid=ASTN.A80...,Spayed,Female,78735,30.251613,-97.883148
4,A808185,"BAHAN DRIVE 78617\n(30.157123, -97.611102)",Yes (come to the shelter),11/05/2019,English Bulldog,Brown/White,3 years,http://www.petharbor.com/pet.asp?uaid=ASTN.A80...,Intact,Female,78617,30.157123,-97.611102
5,A808112,SOUTH WEST FIRST STREET\nAUSTIN 78745,Yes (come to the shelter),11/04/2019,Pit Bull/Labrador Retriever,White/Blue,5 months,http://www.petharbor.com/pet.asp?uaid=ASTN.A80...,Intact,Female,78745,None,None
6,A808213,10015 LAKE CREEK PARKWAY\nAUSTIN 78729\n(30.46...,Yes (come to the shelter),11/06/2019,Chihuahua Longhair,Tan,2 years,http://www.petharbor.com/pet.asp?uaid=ASTN.A80...,Neutered,Male,78729,30.467082,-97.787465

In [3]:
#Import Intakes csv
intakes_df = pd.read_csv("AAC_Intake.csv")

#Select rows where Type= "Dog"
intakes_df = intakes_df.loc[intakes_df['Animal Type'] == 'Dog']

#Select columns ('Animal ID','Name','DateTime','Found Location','Intake Type','Intake Condition','Sex upon Intake','Age upon Intake','Breed','Color')
intakes_df = intakes_df[['Animal ID',
                        'DateTime',
                        'Found Location',
                        'Intake Type',
                        'Intake Condition',
                        'Sex upon Intake',
                        'Age upon Intake',
                        'Breed',
                        'Color']]

#Rename datetime column
intakes_df.rename(columns = {'DateTime': 'Intake_Date'}, inplace = True)

##Split Sex Upon intake column into gender and intake sex
#split value of Sex upon intake column
intake_sex_split = intakes_df['Sex upon Intake'].str.split(" ", n = 1, expand = True) 
  
# making separate intske sex column from new data frame 
intakes_df["Intake_Sex"]= intake_sex_split[0] 
  
# making separate gender column from new data frame 
intakes_df["Gender"]= intake_sex_split[1] 
  
# Dropping old Sex upon intake column
intakes_df.drop(columns =['Sex upon Intake'], inplace = True) 


##Split Found location column into address, city, state
#split value of location column on (
intake_loc_split = intakes_df['Found Location'].str.split("(", n = 1, expand = True) 
  
# making separate state column from new data frame
intakes_df["Found State"] = intake_loc_split[1].str.replace(')', '')

#split intake_loc_split[0] on " in "
intake_street_split = intake_loc_split[0].str.split(" in ", n = 1, expand = True) 
  
#Sort by Animal ID, then by intake date
intakes_df.sort_values(by=["Animal ID", "Intake_Date"], ascending=[True, True], inplace=True)

intakes_df.head()

,Animal ID,Intake_Date,Found Location,Intake Type,Intake Condition,Age upon Intake,Breed,Color,Intake_Sex,Gender,Found State
68624,A006100,03/07/2014 02:26:00 PM,8700 Research in Austin (TX),Public Assist,Normal,6 years,Spinone Italiano Mix,Yellow/White,Neutered,Male,TX
15226,A006100,12/07/2017 02:07:00 PM,Colony Creek And Hunters Trace in Austin (TX),Stray,Normal,10 years,Spinone Italiano Mix,Yellow/White,Neutered,Male,TX
3258,A006100,12/19/2014 10:21:00 AM,8700 Research Blvd in Austin (TX),Public Assist,Normal,7 years,Spinone Italiano Mix,Yellow/White,Neutered,Male,TX
53387,A047759,04/02/2014 03:55:00 PM,Austin (TX),Owner Surrender,Normal,10 years,Dachshund,Tricolor,Neutered,Male,TX
72565,A134067,11/16/2013 09:02:00 AM,12034 Research Blvd in Austin (TX),Public Assist,Injured,16 years,Shetland Sheepdog,Brown/White,Neutered,Male,TX

In [4]:
##Split Found location column into street, city, state
found_street = []
found_city = []

#Code below is an attempt to sort street vs. city values correctly
#Loop through intake_loc_split[0] values
for string in intake_loc_split[0]:
    #If " in " exists in string then split street/city on " in "
    if " in " in string:
        #split strong on " in "
        intake_street_split = string.split(" in ", 1) 

        # append 
        found_street.append(intake_street_split[0])
        found_city.append(intake_street_split[1])

    #If not then place string in "found city"
    else:
        found_street.append('none')
        found_city.append(string)
        
#add city and street columns to intakes-df
intakes_df["Found City"] = found_city
intakes_df["Found Street"] = found_street

#create date index list
date_ID = []

#check if the current Animal ID is the same as the 1 before it
match = intakes_df['Animal ID'].eq(intakes_df['Animal ID'].shift())

#loop through df
for i in match:
    #if the current Animal ID is the same as the 1 before it...
    if i == True:
        #add 1 to dateid
        dateid += 1
    #if not...
    else:
        #start dateid as 1
        dateid = 1
    #append dateid value to date_ID list
    date_ID.append(dateid)
    
#add date_ID to df
intakes_df['Date_ID'] = date_ID

intakes_df.head(20)

,Animal ID,Intake_Date,Found Location,Intake Type,Intake Condition,Age upon Intake,Breed,Color,Intake_Sex,Gender,Found State,Found City,Found Street,Date_ID
68624,A006100,03/07/2014 02:26:00 PM,8700 Research in Austin (TX),Public Assist,Normal,6 years,Spinone Italiano Mix,Yellow/White,Neutered,Male,TX,Austin,2501 Magin Meadow Dr,1
15226,A006100,12/07/2017 02:07:00 PM,Colony Creek And Hunters Trace in Austin (TX),Stray,Normal,10 years,Spinone Italiano Mix,Yellow/White,Neutered,Male,TX,Austin,9409 Bluegrass Dr,2
3258,A006100,12/19/2014 10:21:00 AM,8700 Research Blvd in Austin (TX),Public Assist,Normal,7 years,Spinone Italiano Mix,Yellow/White,Neutered,Male,TX,Austin,2818 Palomino Trail,3
53387,A047759,04/02/2014 03:55:00 PM,Austin (TX),Owner Surrender,Normal,10 years,Dachshund,Tricolor,Neutered,Male,TX,Austin,800 Grove Blvd,1
72565,A134067,11/16/2013 09:02:00 AM,12034 Research Blvd in Austin (TX),Public Assist,Injured,16 years,Shetland Sheepdog,Brown/White,Neutered,Male,TX,Austin,none,1
31358,A141142,11/16/2013 02:46:00 PM,Austin (TX),Stray,Aged,15 years,Labrador Retriever/Pit Bull,Black/White,Spayed,Female,TX,Austin,415 East Mary Street,1
96273,A163459,11/14/2014 03:11:00 PM,Ih 35 And 41St St in Austin (TX),Stray,Normal,15 years,Miniature Schnauzer Mix,Black/Gray,Intact,Female,TX,Austin,none,1
12765,A165752,09/15/2014 11:28:00 AM,Gatlin Gun Rd And Brodie in Austin (TX),Stray,Normal,15 years,Lhasa Apso Mix,Brown/White,Neutered,Male,TX,Austin,8800 South First Street,1
48978,A178569,03/17/2014 09:45:00 AM,Austin (TX),Public Assist,Normal,15 years,Shetland Sheepdog Mix,White/Black,Neutered,Male,TX,Manor,Galilee Court And Damita Jo Dr,1
33166,A189592,09/18/2015 05:46:00 PM,Chesney And Slaughter in Austin (TX),Stray,Normal,18 years,Shetland Sheepdog Mix,Brown/White,Spayed,Female,TX,Austin,9705 Thaxton,1
80274,A200922,10/03/2013 03:47:00 PM,Austin (TX),Owner Surrender,Normal,16 years,Dachshund Mix,Black/Tan,Neutered,Male,TX,Austin,1501 S Fm 973,1
97339,A208755,02/17/2015 01:17:00 PM,Austin (TX),Owner Surrender,Sick,14 years,Border Collie Mix,Black/White,Neutered,Male,TX,Austin,1801 Westridge,1
62571,A210457,09/28/2016 12:05:00 PM,4424 S Mopac #412 in Austin (TX),Public Assist,Aged,17 years,Chihuahua Shorthair,Tan/Black,Neutered,Male,TX,Austin,7500 South Interstate 35,1
9377,A212672,11/25/2013 05:18:00 PM,14611 Wells Port Dr in Austin (TX),Stray,Normal,13 years,German Shepherd/Labrador Retriever,Tan/Black,Intact,Female,TX,Austin,3737 Keats Dr,1
44387,A215368,08/04/2014 01:51:00 PM,Clay/Ulrich in Austin (TX),Stray,Normal,13 years,Newfoundland Mix,Black,Neutered,Male,TX,Austin,East Pleasant Valley And Stassney,1
59085,A218622,12/02/2013 03:33:00 PM,Austin (TX),Owner Surrender,Sick,15 years,Pug,Gold/Gold,Neutered,Male,TX,Austin,4800 Cottonwood St,1
65831,A218624,12/02/2013 03:33:00 PM,Austin (TX),Owner Surrender,Sick,15 years,Pug,Gold/Gold,Neutered,Male,TX,Austin,Guadalupe/St. Johns,1
89859,A221327,04/28/2015 03:08:00 PM,7400 Arrowmound in Austin (TX),Stray,Injured,16 years,Staffordshire Mix,Brown/White,Spayed,Female,TX,Austin,none,1
67161,A221448,10/27/2013 11:17:00 AM,Silver Spring Dr And Mesa Dr in Austin (TX),Stray,Normal,12 years,Labrador Retriever Mix,Brown/White,Neutered,Male,TX,Travis,17833 Basket Flower Bend,1
85381,A226069,10/06/2015 12:29:00 PM,Wheless Ln And Berkman Dr in Austin (TX),Stray,Normal,15 years,Labrador Retriever/Beagle,Sable/White,Neutered,Male,TX,Austin,4200 Smith School Rd,1

In [5]:
#Add found location to found_df
found_loc_df = found_df.merge(intakes_df, how='inner', on='Animal ID')

#reorder columns
found_loc_df = found_loc_df[['Animal ID', 
                             'Found Street',
                           'Found City',
                           'Found State',
                             'Zip_code',
                             'Latitude',
                             'Longitude',
                             'At AAC', 
                             'Intake Date',
                             'Breed(unconfirmed)', 
                             'Color_x',
                             'Found_Sex',
                             'Gender_x',
                             'Age',
                             'Image Link']]

found_loc_df.head()
#found_loc_df.count()

#found_loc_df['At AAC'].value_counts()

#to csv
found_loc_df.to_csv('AAC_Found_Final.csv', index= False)

In [6]:
#Import Outcomes csv
outcomes_df = pd.read_csv("AAC_Outcome.csv")

#Select rows where Type= "Dog"
outcomes_df = outcomes_df.loc[outcomes_df['Animal Type'] == 'Dog']


#Select columns ('Animal ID', 'Name', 'DateTime', 'Date of Birth', 'Outcome Type', 'Outcome Subtype', 'Sex upon Outcome', 'Age upon Outcome', 'Breed', 'Color')
outcomes_df = outcomes_df[['Animal ID', 
                          'Name', 
                          'DateTime', 
                          'Date of Birth', 
                          'Outcome Type', 
                          'Sex upon Outcome', 
                          'Age upon Outcome']]

#Rename datetime column
outcomes_df.rename(columns = {'DateTime': 'Outcome_Date'}, inplace = True)

#Split Sex column into gender and outcome sex. Remove Gender column
#split value of Sex upon outcome column
outcome_sex_split = outcomes_df['Sex upon Outcome'].str.split(" ", n = 1, expand = True) 
  
# making separate sex outcome column from new data frame 
outcomes_df["Outcome_Sex"]= outcome_sex_split[0] 
  
# Dropping old sex upon outcome column
outcomes_df.drop(columns =['Sex upon Outcome'], inplace = True) 

#Remove * from Names
outcomes_df['Name'] = outcomes_df['Name'].str.replace('*','')

#Sort by Animal ID, then by outcome date
outcomes_df.sort_values(by=["Animal ID", "Outcome_Date"], ascending=[True, True], inplace=True)

#create date index list
date_ID = []

#check if the current Animal ID is the same as the 1 before it
match = outcomes_df['Animal ID'].eq(outcomes_df['Animal ID'].shift())

#loop through df
for i in match:
    #if the current Animal ID is the same as the 1 before it...
    if i == True:
        #add 1 to dateid
        dateid += 1
    #if not...
    else:
        #start dateid as 1
        dateid = 1
    #append dateid value to date_ID list
    date_ID.append(dateid)
    
#add date_ID to df
outcomes_df['Date_ID'] = date_ID

from datetime import datetime

def diff_month(d1, d2):
    return (d1.year - d2.year) * 12 + d1.month - d2.month

#convert to datetime
outcomes_df["Outcome_Date"] = pd.to_datetime(outcomes_df["Outcome_Date"])
outcomes_df["Date of Birth"] = pd.to_datetime(outcomes_df["Date of Birth"])

age_months = []

#loop through outcome_df rows
for index, row in outcomes_df.iterrows():
    #find duration(age) in months
    age = diff_month(row["Outcome_Date"], row["Date of Birth"])
    #append age value to list
    age_months.append(age)
    
#add age in months to df
outcomes_df['Outcome_Age_Months'] = age_months

outcomes_df.head()
#outcomes_df['Animal ID'].value_counts()
#outcomes_df.info()

,Animal ID,Name,Outcome_Date,Date of Birth,Outcome Type,Age upon Outcome,Outcome_Sex,Date_ID,Outcome_Age_Months
63810,A006100,Scamp,2014-03-08 17:10:00,2007-07-09,Return to Owner,6 years,Neutered,1,80
101761,A006100,Scamp,2017-12-07 00:00:00,2007-07-09,Return to Owner,10 years,Neutered,2,125
36835,A006100,Scamp,2014-12-20 16:35:00,2007-07-09,Return to Owner,7 years,Neutered,3,89
25192,A047759,Oreo,2014-04-07 15:12:00,2004-04-02,Transfer,10 years,Neutered,1,120
48392,A134067,Bandit,2013-11-16 11:54:00,1997-10-16,Return to Owner,16 years,Neutered,1,193

In [7]:
#Import Cats vs. Dogs csv
catsvdogs_df = pd.read_csv("catsvdogs.csv")

#Select rows where Location=Texas
#catsvdogs_df = catsvdogs_df.loc[catsvdogs_df['Location'] == 'Texas']

#Select columns ('Location','Number of Households (in 1000)','Percentage of households with pets''Number of Pet Households (in 1000)','Percentage of Dog Owners','Dog Owning Households (1000s)','Mean Number of Dogs per household','Dog Population (in 1000)')
catsvdogs_df = catsvdogs_df[['Location',
                            'Number of Households (in 1000)',
                            'Percentage of households with pets',
                            'Number of Pet Households (in 1000)',
                            'Percentage of Dog Owners',
                            'Dog Owning Households (1000s)',
                            'Mean Number of Dogs per household',
                            'Dog Population (in 1000)']]

catsvdogs_df.head()

#to csv
catsvdogs_df.to_csv('Pet_Dogs_Final.csv', index= False)

In [8]:
#Merge DataFrames (intake, outcome, found?)
merged_df = pd.merge(intakes_df, outcomes_df, how='inner', on=['Animal ID','Date_ID'])

##merge (or zip) each row w/ condition
#merge this instance of Animal ID(intake) with the next same instance of animal id(outcome)
#if theres not an equal ID, move to the next 1

#Split color by "/" (color 1, color2, color3)
#split value of color column
merged_color_split = merged_df['Color'].str.split("/", n = 2, expand = True) 
  
# making separate color1 column from new data frame 
merged_df["Color1"]= merged_color_split[0] 

# making separate color2 column from new data frame 
merged_df["Color2"]= merged_color_split[1] 

# making separate color3 column from new data frame 
#merged_df["Color3"]= merged_color_split[2]
  
# Dropping old color column
merged_df.drop(columns =['Color'], inplace = True) 

#create breed lists
breed1 =[]
breed2 = []

#Split breed (breed1, breed2, breed3)
for breed in merged_df['Breed']:
    if "/" in breed:
        #split value of breed column
        merged_breed_split = breed.split("/", 2) 

        # making separate breed1 column from new data frame 
        breed1.append(merged_breed_split[0])

        # making separate breed2 column from new data frame 
        breed2.append(merged_breed_split[1])
        
    elif "Mix" in breed: 
        # making separate breed1 column from new data frame 
        breed1.append(breed[:-3])

        # making separate breed2 column from new data frame 
        breed2.append(breed[-3:])
    
    else:
        # making separate breed1 column from new data frame 
        breed1.append(breed)

        # making separate breed2 column from new data frame 
        breed2.append("none")

# making separate breed3 column from new data frame 
#merged_df["Breed3"] = merged_breed_split[2]

#add breed1 and breed2 columns to df
merged_df['Breed1'] = breed1
merged_df['Breed2'] = breed2
  
# Dropping old breed column
merged_df.drop(columns = ['Breed'], inplace = True) 


#Create Duration of Stay column
#convert columns to datetime type
merged_df["Outcome_Date"] = pd.to_datetime(merged_df["Outcome_Date"])
merged_df["Intake_Date"] = pd.to_datetime(merged_df["Intake_Date"])

#subtract intake and outcome dates to form duration column
merged_df["AAC_Duration"] = (merged_df["Outcome_Date"] - merged_df["Intake_Date"])


#Remove NaN rows or replace NaN values
merged_df['Name'].fillna("none", inplace = True)
merged_df['Color2'].fillna("none", inplace = True)
merged_df.dropna(inplace=True)

#Remove rows with negative duration
merged_df1 = merged_df[merged_df.AAC_Duration > dt.timedelta(minutes=0)]
merged_df1 = merged_df[merged_df.AAC_Duration > dt.timedelta(days=0)]

#Reorder columns
merged_df1 = merged_df[['Animal ID', 
                      'Name', 
                      'Date of Birth',
                       'Gender',
                       'Color1',
                       'Color2',
                       'Breed1',
                       'Breed2',
                       'Found Street',
                       'Found City',
                       'Found State',
                       'Intake_Date',
                       'Intake Type',
                       'Intake Condition',
                       'Age upon Intake',
                       'Intake_Sex',
                       'Outcome_Date',
                      'Outcome Type', 
                      'Age upon Outcome',
                        'Outcome_Age_Months',
                       'Outcome_Sex', 
                       'AAC_Duration']]

merged_df1.head(15)

,Animal ID,Name,Date of Birth,Gender,Color1,Color2,Breed1,Breed2,Found Street,Found City,...,Intake Type,Intake Condition,Age upon Intake,Intake_Sex,Outcome_Date,Outcome Type,Age upon Outcome,Outcome_Age_Months,Outcome_Sex,AAC_Duration
0,A006100,Scamp,2007-07-09,Male,Yellow,White,Spinone Italiano,Mix,2501 Magin Meadow Dr,Austin,...,Public Assist,Normal,6 years,Neutered,2014-03-08 17:10:00,Return to Owner,6 years,80,Neutered,1 days 02:44:00
1,A006100,Scamp,2007-07-09,Male,Yellow,White,Spinone Italiano,Mix,9409 Bluegrass Dr,Austin,...,Stray,Normal,10 years,Neutered,2017-12-07 00:00:00,Return to Owner,10 years,125,Neutered,-1 days +09:53:00
2,A006100,Scamp,2007-07-09,Male,Yellow,White,Spinone Italiano,Mix,2818 Palomino Trail,Austin,...,Public Assist,Normal,7 years,Neutered,2014-12-20 16:35:00,Return to Owner,7 years,89,Neutered,1 days 06:14:00
3,A047759,Oreo,2004-04-02,Male,Tricolor,none,Dachshund,none,800 Grove Blvd,Austin,...,Owner Surrender,Normal,10 years,Neutered,2014-04-07 15:12:00,Transfer,10 years,120,Neutered,4 days 23:17:00
4,A134067,Bandit,1997-10-16,Male,Brown,White,Shetland Sheepdog,none,none,Austin,...,Public Assist,Injured,16 years,Neutered,2013-11-16 11:54:00,Return to Owner,16 years,193,Neutered,0 days 02:52:00
5,A141142,Bettie,1998-06-01,Female,Black,White,Labrador Retriever,Pit Bull,415 East Mary Street,Austin,...,Stray,Aged,15 years,Spayed,2013-11-17 11:40:00,Return to Owner,15 years,185,Spayed,0 days 20:54:00
6,A163459,Sasha,1999-10-19,Female,Black,Gray,Miniature Schnauzer,Mix,none,Austin,...,Stray,Normal,15 years,Intact,2014-11-14 19:28:00,Return to Owner,15 years,181,Intact,0 days 04:17:00
7,A165752,Pep,1999-08-18,Male,Brown,White,Lhasa Apso,Mix,8800 South First Street,Austin,...,Stray,Normal,15 years,Neutered,2014-09-15 16:35:00,Return to Owner,15 years,181,Neutered,0 days 05:07:00
8,A178569,Boti,1999-03-17,Male,White,Black,Shetland Sheepdog,Mix,Galilee Court And Damita Jo Dr,Manor,...,Public Assist,Normal,15 years,Neutered,2014-03-23 15:57:00,Return to Owner,15 years,180,Neutered,6 days 06:12:00
9,A189592,Ophelia,1997-08-01,Female,Brown,White,Shetland Sheepdog,Mix,9705 Thaxton,Austin,...,Stray,Normal,18 years,Spayed,2015-09-18 19:04:00,Return to Owner,18 years,217,Spayed,0 days 01:18:00
10,A200922,Carlos,1997-10-03,Male,Black,Tan,Dachshund,Mix,1501 S Fm 973,Austin,...,Owner Surrender,Normal,16 years,Neutered,2013-11-22 09:44:00,Adoption,16 years,193,Neutered,49 days 17:57:00
11,A208755,Kootrie,2000-04-27,Male,Black,White,Border Collie,Mix,1801 Westridge,Austin,...,Owner Surrender,Sick,14 years,Neutered,2015-02-17 16:25:00,Euthanasia,14 years,178,Neutered,0 days 03:08:00
12,A210457,Caleb,1999-06-01,Male,Tan,Black,Chihuahua Shorthair,none,7500 South Interstate 35,Austin,...,Public Assist,Aged,17 years,Neutered,2016-10-07 12:34:00,Adoption,17 years,208,Neutered,9 days 00:29:00
13,A212672,Cujo,2000-03-05,Female,Tan,Black,German Shepherd,Labrador Retriever,3737 Keats Dr,Austin,...,Stray,Normal,13 years,Intact,2013-12-06 14:34:00,Return to Owner,13 years,165,Intact,10 days 21:16:00
14,A215368,Guiness,2001-01-17,Male,Black,none,Newfoundland,Mix,East Pleasant Valley And Stassney,Austin,...,Stray,Normal,13 years,Neutered,2014-08-04 16:31:00,Return to Owner,13 years,163,Neutered,0 days 02:40:00

In [9]:
#Print column count and type
#print(merged_df1.info())

print(merged_df1['Animal ID'].value_counts())

#Export to csv
merged_df1.to_csv('AAC_In_Out_Final.csv', index= False)

/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)

A721033    33
A718223    14
A718877    12
A706536    11
A716018     9
A733594     8
A670612     8
A616444     8
A738324     8
A694501     8
A717053     8
A761266     8
A693283     8
A753618     7
A678294     7
A742421     7
A705625     7
A720278     7
A593537     7
A665334     7
A737814     7
A704287     7
A735601     7
A667894     7
A615920     7
A701265     7
A701901     7
A738073     7
A790435     7
A784785     7
           ..
A687260     1
A581788     1
A765621     1
A696537     1
A774644     1
A793088     1
A679513     1
A770039     1
A802826     1
A777182     1
A691902     1
A775958     1
A697243     1
A724376     1
A786515     1
A690391     1
A741896     1
A772435     1
A704725     1
A764642     1
A671448     1
A589084     1
A797892     1
A704262     1
A806277     1
A674477     1
A770822     1
A684199     1
A754125     1
A778263     1
Name: Animal ID, Length: 51884, dtype: int64

# LOAD

In [10]:
#load to SQL