# TRANSFORM

if duration is negative, remove row? (merged_df)

In [1]:
import pandas as pd
import datetime as dt

In [2]:
#Import Found csv
found_df = pd.read_csv("AAC_Found.csv")

#Select rows where Type= "Dog"
found_df = found_df.loc[found_df['Type'] == 'Dog']

#Select columns ('Animal ID', 'Found Location', 'At AAC', 'Intake Date', 'Looks Like', 'Color','Sex','Age','Image Link')
found_df = found_df[['Animal ID', 
                     'Found Location', 
                     'At AAC', 
                     'Intake Date',
                     'Looks Like', 
                     'Color',
                     'Sex',
                     'Age',
                     'Image Link']]

#Rename looks like column
found_df.rename(columns = {'Looks Like': 'Breed(unconfirmed)'}, inplace = True)

#Split Sex column into gender and found sex
#split value of Sex upon intake column
found_sex_split = found_df['Sex'].str.split(" ", n = 1, expand = True) 
  
# making separate intake sex column from new data frame 
found_df["Found_Sex"]= found_sex_split[0] 

# making separate gender column from new data frame 
found_df["Gender"]= found_sex_split[1] 
  
# Dropping old Sex upon intake column
found_df.drop(columns =['Sex'], inplace = True) 

#Split Found Location column into address and coordinates
#split value of found location column
found_loc_split = found_df['Found Location'].str.split("(", n = 1, expand = True) 
  
# making separate address column from new data frame 
address = found_loc_split[0].str.rstrip()

#Extract zip code (last 5 characters of address)
found_df["Zip_code"] = address.str[-5:]

#split Lat/Long on ","
found_coord_split = found_loc_split[1].str.split(",", n = 1, expand = True) 
# making separate coordinate columns from new data frame 
found_df["Latitude"] = found_coord_split[0] 
found_df["Longitude"] = found_coord_split[1].str.replace(')', '') 


found_df.head()

#found_df.count()

,Animal ID,Found Location,At AAC,Intake Date,Breed(unconfirmed),Color,Age,Image Link,Found_Sex,Gender,Zip_code,Latitude,Longitude
2,A808186,"BAHAN DRIVE 78617\n(30.157123, -97.611102)",Yes (come to the shelter),11/05/2019,English Bulldog,Brown/White,1 year,http://www.petharbor.com/pet.asp?uaid=ASTN.A80...,Intact,Female,78617,30.157123,-97.611102
3,A807919,"6001 OLEANDAR TRAIL\nAUSTIN 78735\n(30.251613,...",Yes (come to the shelter),11/01/2019,Chihuahua Shorthair,White,5 years,http://www.petharbor.com/pet.asp?uaid=ASTN.A80...,Spayed,Female,78735,30.251613,-97.883148
4,A808185,"BAHAN DRIVE 78617\n(30.157123, -97.611102)",Yes (come to the shelter),11/05/2019,English Bulldog,Brown/White,3 years,http://www.petharbor.com/pet.asp?uaid=ASTN.A80...,Intact,Female,78617,30.157123,-97.611102
5,A808112,SOUTH WEST FIRST STREET\nAUSTIN 78745,Yes (come to the shelter),11/04/2019,Pit Bull/Labrador Retriever,White/Blue,5 months,http://www.petharbor.com/pet.asp?uaid=ASTN.A80...,Intact,Female,78745,None,None
6,A808213,10015 LAKE CREEK PARKWAY\nAUSTIN 78729\n(30.46...,Yes (come to the shelter),11/06/2019,Chihuahua Longhair,Tan,2 years,http://www.petharbor.com/pet.asp?uaid=ASTN.A80...,Neutered,Male,78729,30.467082,-97.787465

In [3]:
#Import Intakes csv
intakes_df = pd.read_csv("AAC_Intake.csv")

#Select rows where Type= "Dog"
intakes_df = intakes_df.loc[intakes_df['Animal Type'] == 'Dog']

#Select columns ('Animal ID','Name','DateTime','Found Location','Intake Type','Intake Condition','Sex upon Intake','Age upon Intake','Breed','Color')
intakes_df = intakes_df[['Animal ID',
                        'DateTime',
                        'Found Location',
                        'Intake Type',
                        'Intake Condition',
                        'Sex upon Intake',
                        'Age upon Intake',
                        'Breed',
                        'Color']]

#Rename datetime column
intakes_df.rename(columns = {'DateTime': 'Intake_Date'}, inplace = True)

##Split Sex Upon intake column into gender and intake sex
#split value of Sex upon intake column
intake_sex_split = intakes_df['Sex upon Intake'].str.split(" ", n = 1, expand = True) 
  
# making separate intske sex column from new data frame 
intakes_df["Intake_Sex"]= intake_sex_split[0] 
  
# making separate gender column from new data frame 
intakes_df["Gender"]= intake_sex_split[1] 
  
# Dropping old Sex upon intake column
intakes_df.drop(columns =['Sex upon Intake'], inplace = True) 


##Split Found location column into address, city, state
#split value of location column on (
intake_loc_split = intakes_df['Found Location'].str.split("(", n = 1, expand = True) 
  
# making separate state column from new data frame
intakes_df["Found State"] = intake_loc_split[1].str.replace(')', '')

#split intake_loc_split[0] on " in "
intake_street_split = intake_loc_split[0].str.split(" in ", n = 1, expand = True) 
  
# making separate street/city columns from new data frame. Only works for values w/ street AND city.
#intakes_df["Found Street"]= intake_street_split[0] 
#intakes_df["Found City"]= intake_street_split[1] 

intakes_df.head(20)

,Animal ID,Intake_Date,Found Location,Intake Type,Intake Condition,Age upon Intake,Breed,Color,Intake_Sex,Gender,Found State
0,A786884,01/03/2019 04:19:00 PM,2501 Magin Meadow Dr in Austin (TX),Stray,Normal,2 years,Beagle Mix,Tricolor,Neutered,Male,TX
1,A706918,07/05/2015 12:59:00 PM,9409 Bluegrass Dr in Austin (TX),Stray,Normal,8 years,English Springer Spaniel,White/Liver,Spayed,Female,TX
2,A724273,04/14/2016 06:43:00 PM,2818 Palomino Trail in Austin (TX),Stray,Normal,11 months,Basenji Mix,Sable/White,Intact,Male,TX
4,A682524,06/29/2014 10:38:00 AM,800 Grove Blvd in Austin (TX),Stray,Normal,4 years,Doberman Pinsch/Australian Cattle Dog,Tan/Gray,Neutered,Male,TX
5,A743852,02/18/2017 12:46:00 PM,Austin (TX),Owner Surrender,Normal,2 years,Labrador Retriever Mix,Chocolate,Neutered,Male,TX
6,A635072,04/16/2019 09:53:00 AM,415 East Mary Street in Austin (TX),Public Assist,Normal,6 years,Great Dane Mix,Black,Neutered,Male,TX
7,A708452,07/30/2015 02:37:00 PM,Austin (TX),Public Assist,Normal,2 years,Labrador Retriever Mix,Black/White,Intact,Male,TX
10,A760053,10/11/2017 03:46:00 PM,8800 South First Street in Austin (TX),Stray,Normal,2 years,Chihuahua Shorthair,White/Tan,Intact,Male,TX
11,A707375,07/11/2015 06:19:00 PM,Galilee Court And Damita Jo Dr in Manor (TX),Stray,Normal,5 months,Pit Bull,Brown/White,Intact,Female,TX
12,A696408,02/04/2015 12:58:00 PM,9705 Thaxton in Austin (TX),Stray,Normal,2 years,Chihuahua Shorthair,Tricolor,Intact,Female,TX
19,A697950,03/04/2015 11:22:00 AM,1501 S Fm 973 in Austin (TX),Stray,Normal,2 months,Australian Cattle Dog/Labrador Retriever,Tan/White,Intact,Female,TX
20,A298074,09/06/2015 02:21:00 PM,1801 Westridge in Austin (TX),Stray,Normal,18 years,Parson Russell Terrier Mix,Black/White,Spayed,Female,TX
21,A769764,04/09/2018 07:03:00 PM,7500 South Interstate 35 in Austin (TX),Stray,Normal,5 months,Yorkshire Terrier Mix,White/Black,Intact,Female,TX
23,A682230,06/25/2014 04:27:00 PM,3737 Keats Dr in Austin (TX),Stray,Normal,5 months,Maltese Mix,White,Intact,Female,TX
24,A749436,05/15/2017 09:50:00 AM,East Pleasant Valley And Stassney in Austin (TX),Stray,Normal,4 months,Dachshund Mix,Brown/White,Intact,Male,TX
27,A759935,10/09/2017 10:39:00 PM,4800 Cottonwood St in Austin (TX),Stray,Normal,1 month,Labrador Retriever Mix,Black,Intact,Female,TX
28,A666877,11/08/2013 03:24:00 PM,Guadalupe/St. Johns in Austin (TX),Stray,Normal,1 year,Dachshund Mix,Tan/White,Intact,Male,TX
30,A732903,08/14/2016 03:02:00 PM,Austin (TX),Stray,Injured,2 months,Labrador Retriever Mix,Black/White,Intact,Female,TX
34,A769816,04/10/2018 04:46:00 PM,17833 Basket Flower Bend in Travis (TX),Stray,Normal,5 years,Plott Hound Mix,Brown Brindle/White,Intact,Male,TX
36,A700396,12/07/2015 09:11:00 AM,4200 Smith School Rd in Austin (TX),Stray,Normal,3 years,Pit Bull Mix,Black/White,Spayed,Female,TX

In [4]:
##Split Found location column into street, city, state
found_street = []
found_city = []

#Code below is an attempt to sort street vs. city values correctly
#Loop through intake_loc_split[0] values
for string in intake_loc_split[0]:
    #If " in " exists in string then split street/city on " in "
    if " in " in string:
        #split strong on " in "
        intake_street_split = string.split(" in ", 1) 

        # append 
        found_street.append(intake_street_split[0])
        found_city.append(intake_street_split[1])

    #If not then place string in "found city"
    else:
        found_street.append('none')
        found_city.append(string)
        
#add city and street columns to intakes-df
intakes_df["Found City"] = found_city
intakes_df["Found Street"] = found_street

intakes_df.head(20)

,Animal ID,Intake_Date,Found Location,Intake Type,Intake Condition,Age upon Intake,Breed,Color,Intake_Sex,Gender,Found State,Found City,Found Street
0,A786884,01/03/2019 04:19:00 PM,2501 Magin Meadow Dr in Austin (TX),Stray,Normal,2 years,Beagle Mix,Tricolor,Neutered,Male,TX,Austin,2501 Magin Meadow Dr
1,A706918,07/05/2015 12:59:00 PM,9409 Bluegrass Dr in Austin (TX),Stray,Normal,8 years,English Springer Spaniel,White/Liver,Spayed,Female,TX,Austin,9409 Bluegrass Dr
2,A724273,04/14/2016 06:43:00 PM,2818 Palomino Trail in Austin (TX),Stray,Normal,11 months,Basenji Mix,Sable/White,Intact,Male,TX,Austin,2818 Palomino Trail
4,A682524,06/29/2014 10:38:00 AM,800 Grove Blvd in Austin (TX),Stray,Normal,4 years,Doberman Pinsch/Australian Cattle Dog,Tan/Gray,Neutered,Male,TX,Austin,800 Grove Blvd
5,A743852,02/18/2017 12:46:00 PM,Austin (TX),Owner Surrender,Normal,2 years,Labrador Retriever Mix,Chocolate,Neutered,Male,TX,Austin,none
6,A635072,04/16/2019 09:53:00 AM,415 East Mary Street in Austin (TX),Public Assist,Normal,6 years,Great Dane Mix,Black,Neutered,Male,TX,Austin,415 East Mary Street
7,A708452,07/30/2015 02:37:00 PM,Austin (TX),Public Assist,Normal,2 years,Labrador Retriever Mix,Black/White,Intact,Male,TX,Austin,none
10,A760053,10/11/2017 03:46:00 PM,8800 South First Street in Austin (TX),Stray,Normal,2 years,Chihuahua Shorthair,White/Tan,Intact,Male,TX,Austin,8800 South First Street
11,A707375,07/11/2015 06:19:00 PM,Galilee Court And Damita Jo Dr in Manor (TX),Stray,Normal,5 months,Pit Bull,Brown/White,Intact,Female,TX,Manor,Galilee Court And Damita Jo Dr
12,A696408,02/04/2015 12:58:00 PM,9705 Thaxton in Austin (TX),Stray,Normal,2 years,Chihuahua Shorthair,Tricolor,Intact,Female,TX,Austin,9705 Thaxton
19,A697950,03/04/2015 11:22:00 AM,1501 S Fm 973 in Austin (TX),Stray,Normal,2 months,Australian Cattle Dog/Labrador Retriever,Tan/White,Intact,Female,TX,Austin,1501 S Fm 973
20,A298074,09/06/2015 02:21:00 PM,1801 Westridge in Austin (TX),Stray,Normal,18 years,Parson Russell Terrier Mix,Black/White,Spayed,Female,TX,Austin,1801 Westridge
21,A769764,04/09/2018 07:03:00 PM,7500 South Interstate 35 in Austin (TX),Stray,Normal,5 months,Yorkshire Terrier Mix,White/Black,Intact,Female,TX,Austin,7500 South Interstate 35
23,A682230,06/25/2014 04:27:00 PM,3737 Keats Dr in Austin (TX),Stray,Normal,5 months,Maltese Mix,White,Intact,Female,TX,Austin,3737 Keats Dr
24,A749436,05/15/2017 09:50:00 AM,East Pleasant Valley And Stassney in Austin (TX),Stray,Normal,4 months,Dachshund Mix,Brown/White,Intact,Male,TX,Austin,East Pleasant Valley And Stassney
27,A759935,10/09/2017 10:39:00 PM,4800 Cottonwood St in Austin (TX),Stray,Normal,1 month,Labrador Retriever Mix,Black,Intact,Female,TX,Austin,4800 Cottonwood St
28,A666877,11/08/2013 03:24:00 PM,Guadalupe/St. Johns in Austin (TX),Stray,Normal,1 year,Dachshund Mix,Tan/White,Intact,Male,TX,Austin,Guadalupe/St. Johns
30,A732903,08/14/2016 03:02:00 PM,Austin (TX),Stray,Injured,2 months,Labrador Retriever Mix,Black/White,Intact,Female,TX,Austin,none
34,A769816,04/10/2018 04:46:00 PM,17833 Basket Flower Bend in Travis (TX),Stray,Normal,5 years,Plott Hound Mix,Brown Brindle/White,Intact,Male,TX,Travis,17833 Basket Flower Bend
36,A700396,12/07/2015 09:11:00 AM,4200 Smith School Rd in Austin (TX),Stray,Normal,3 years,Pit Bull Mix,Black/White,Spayed,Female,TX,Austin,4200 Smith School Rd

In [5]:
#Add found location to found_df
found_loc_df = found_df.merge(intakes_df, how='inner', on='Animal ID')

#reorder columns
found_loc_df = found_loc_df[['Animal ID', 
                             'Found Street',
                           'Found City',
                           'Found State',
                             'Zip_code',
                             'Latitude',
                             'Longitude',
                             'At AAC', 
                             'Intake Date',
                             'Breed(unconfirmed)', 
                             'Color_x',
                             'Found_Sex',
                             'Gender_x',
                             'Age',
                             'Image Link']]

found_loc_df.head()
#found_loc_df.count()

#to csv
found_loc_df.to_csv('AAC_Found_Final.csv', index= False)

In [6]:
#Import Outcomes csv
outcomes_df = pd.read_csv("AAC_Outcome.csv")

#Select rows where Type= "Dog"
outcomes_df = outcomes_df.loc[outcomes_df['Animal Type'] == 'Dog']


#Select columns ('Animal ID', 'Name', 'DateTime', 'Date of Birth', 'Outcome Type', 'Outcome Subtype', 'Sex upon Outcome', 'Age upon Outcome', 'Breed', 'Color')
outcomes_df = outcomes_df[['Animal ID', 
                          'Name', 
                          'DateTime', 
                          'Date of Birth', 
                          'Outcome Type', 
                          'Sex upon Outcome', 
                          'Age upon Outcome']]

#Rename datetime column
outcomes_df.rename(columns = {'DateTime': 'Outcome_Date'}, inplace = True)

#Split Sex column into gender and outcome sex. Remove Gender column
#split value of Sex upon outcome column
outcome_sex_split = outcomes_df['Sex upon Outcome'].str.split(" ", n = 1, expand = True) 
  
# making separate sex outcome column from new data frame 
outcomes_df["Outcome_Sex"]= outcome_sex_split[0] 
  
# Dropping old sex upon outcome column
outcomes_df.drop(columns =['Sex upon Outcome'], inplace = True) 

#Remove * from Names
outcomes_df['Name'] = outcomes_df['Name'].str.replace('*','')

outcomes_df.head()

,Animal ID,Name,Outcome_Date,Date of Birth,Outcome Type,Age upon Outcome,Outcome_Sex
0,A789027,Lennie,02/17/2019 11:44:00 AM,02/13/2017,Adoption,2 years,Neutered
1,A720371,Moose,02/13/2016 05:59:00 PM,10/08/2015,Adoption,4 months,Neutered
9,A789027,Lennie,03/10/2019 12:25:00 PM,02/13/2017,Adoption,2 years,Neutered
12,A795059,NaN,05/16/2019 10:14:00 AM,03/15/2019,Euthanasia,2 months,Intact
13,A795043,NaN,05/16/2019 10:17:00 AM,03/31/2019,Euthanasia,1 month,Intact

In [7]:
#Import Cats vs. Dogs csv
catsvdogs_df = pd.read_csv("catsvdogs.csv")

#Select rows where Location=Texas
#catsvdogs_df = catsvdogs_df.loc[catsvdogs_df['Location'] == 'Texas']

#Select columns ('Location','Number of Households (in 1000)','Percentage of households with pets''Number of Pet Households (in 1000)','Percentage of Dog Owners','Dog Owning Households (1000s)','Mean Number of Dogs per household','Dog Population (in 1000)')
catsvdogs_df = catsvdogs_df[['Location',
                            'Number of Households (in 1000)',
                            'Percentage of households with pets',
                            'Number of Pet Households (in 1000)',
                            'Percentage of Dog Owners',
                            'Dog Owning Households (1000s)',
                            'Mean Number of Dogs per household',
                            'Dog Population (in 1000)']]

catsvdogs_df.head()

#to csv
catsvdogs_df.to_csv('Pet_Dogs_Final.csv', index= False)

In [8]:
#Merge DataFrames (intake, outcome, found?)
merged_df = intakes_df.merge(outcomes_df, how='inner', on='Animal ID')

#Split color by "/" (color 1, color2, color3)
#split value of color column
merged_color_split = merged_df['Color'].str.split("/", n = 2, expand = True) 
  
# making separate color1 column from new data frame 
merged_df["Color1"]= merged_color_split[0] 

# making separate color2 column from new data frame 
merged_df["Color2"]= merged_color_split[1] 

# making separate color3 column from new data frame 
#merged_df["Color3"]= merged_color_split[2]
  
# Dropping old color column
merged_df.drop(columns =['Color'], inplace = True) 

#create breed lists
breed1 =[]
breed2 = []

#Split breed (breed1, breed2, breed3)
for breed in merged_df['Breed']:
    if "/" in breed:
        #split value of breed column
        merged_breed_split = breed.split("/", 2) 

        # making separate breed1 column from new data frame 
        breed1.append(merged_breed_split[0])

        # making separate breed2 column from new data frame 
        breed2.append(merged_breed_split[1])
        
    elif "Mix" in breed: 
        # making separate breed1 column from new data frame 
        breed1.append(breed[:-3])

        # making separate breed2 column from new data frame 
        breed2.append(breed[-3:])
    
    else:
        # making separate breed1 column from new data frame 
        breed1.append(breed)

        # making separate breed2 column from new data frame 
        breed2.append("none")

# making separate breed3 column from new data frame 
#merged_df["Breed3"] = merged_breed_split[2]

#add breed1 and breed2 columns to df
merged_df['Breed1'] = breed1
merged_df['Breed2'] = breed2
  
# Dropping old breed column
merged_df.drop(columns = ['Breed'], inplace = True) 


#Create Duration of Stay column
#convert columns to datetime type
merged_df["Outcome_Date"] = pd.to_datetime(merged_df["Outcome_Date"])
merged_df["Intake_Date"] = pd.to_datetime(merged_df["Intake_Date"])

#subtract intake and outcome dates to form duration column
merged_df["AAC_Duration"] = (merged_df["Outcome_Date"] - merged_df["Intake_Date"])


#Remove NaN rows or replace NaN values
merged_df['Name'].fillna("none", inplace = True)
merged_df['Color2'].fillna("none", inplace = True)
merged_df.dropna(inplace=True)

#Remove rows with negative duration
merged_df1 = merged_df[merged_df.AAC_Duration > dt.timedelta(minutes=0)]

#Reorder columns
merged_df1 = merged_df[['Animal ID', 
                      'Name', 
                      'Date of Birth',
                       'Gender',
                       'Color1',
                       'Color2',
                       'Breed1',
                       'Breed2',
                       'Found Street',
                       'Found City',
                       'Found State',
                       'Intake_Date',
                       'Intake Type',
                       'Intake Condition',
                       'Age upon Intake',
                       'Intake_Sex',
                       'Outcome_Date',
                      'Outcome Type', 
                      'Age upon Outcome',
                       'Outcome_Sex', 
                       'AAC_Duration']]

merged_df1.head(15)

,Animal ID,Name,Date of Birth,Gender,Color1,Color2,Breed1,Breed2,Found Street,Found City,...,Intake_Date,Intake Type,Intake Condition,Age upon Intake,Intake_Sex,Outcome_Date,Outcome Type,Age upon Outcome,Outcome_Sex,AAC_Duration
0,A786884,Brock,01/03/2017,Male,Tricolor,none,Beagle,Mix,2501 Magin Meadow Dr,Austin,...,2019-01-03 16:19:00,Stray,Normal,2 years,Neutered,2019-01-08 15:11:00,Transfer,2 years,Neutered,4 days 22:52:00
1,A706918,Belle,07/05/2007,Female,White,Liver,English Springer Spaniel,none,9409 Bluegrass Dr,Austin,...,2015-07-05 12:59:00,Stray,Normal,8 years,Spayed,2015-07-05 15:13:00,Return to Owner,8 years,Spayed,0 days 02:14:00
2,A724273,Runster,04/17/2015,Male,Sable,White,Basenji,Mix,2818 Palomino Trail,Austin,...,2016-04-14 18:43:00,Stray,Normal,11 months,Intact,2016-04-21 17:17:00,Return to Owner,1 year,Neutered,6 days 22:34:00
3,A682524,Rio,06/29/2010,Male,Tan,Gray,Doberman Pinsch,Australian Cattle Dog,800 Grove Blvd,Austin,...,2014-06-29 10:38:00,Stray,Normal,4 years,Neutered,2014-07-02 14:16:00,Return to Owner,4 years,Neutered,3 days 03:38:00
4,A743852,Odin,02/18/2015,Male,Chocolate,none,Labrador Retriever,Mix,none,Austin,...,2017-02-18 12:46:00,Owner Surrender,Normal,2 years,Neutered,2017-02-21 17:44:00,Return to Owner,2 years,Neutered,3 days 04:58:00
5,A635072,Beowulf,06/03/2012,Male,Black,none,Great Dane,Mix,415 East Mary Street,Austin,...,2019-04-16 09:53:00,Public Assist,Normal,6 years,Neutered,2019-04-18 13:45:00,Return to Owner,6 years,Neutered,2 days 03:52:00
6,A708452,Mumble,07/28/2013,Male,Black,White,Labrador Retriever,Mix,none,Austin,...,2015-07-30 14:37:00,Public Assist,Normal,2 years,Intact,2015-08-04 18:17:00,Return to Owner,2 years,Neutered,5 days 03:40:00
7,A760053,none,10/11/2015,Male,White,Tan,Chihuahua Shorthair,none,8800 South First Street,Austin,...,2017-10-11 15:46:00,Stray,Normal,2 years,Intact,2017-10-15 18:30:00,Adoption,2 years,Neutered,4 days 02:44:00
8,A707375,Candy Cane,01/11/2015,Female,Brown,White,Pit Bull,none,Galilee Court And Damita Jo Dr,Manor,...,2015-07-11 18:19:00,Stray,Normal,5 months,Intact,2015-11-28 17:31:00,Adoption,10 months,Spayed,139 days 23:12:00
9,A696408,Pearl,02/04/2013,Female,Tricolor,none,Chihuahua Shorthair,none,9705 Thaxton,Austin,...,2015-02-04 12:58:00,Stray,Normal,2 years,Intact,2015-05-28 11:24:00,Adoption,2 years,Spayed,112 days 22:26:00
10,A697950,none,12/20/2014,Female,Tan,White,Australian Cattle Dog,Labrador Retriever,1501 S Fm 973,Austin,...,2015-03-04 11:22:00,Stray,Normal,2 months,Intact,2015-03-08 18:55:00,Adoption,2 months,Spayed,4 days 07:33:00
11,A298074,Stumpy,02/07/1997,Female,Black,White,Parson Russell Terrier,Mix,1801 Westridge,Austin,...,2015-09-06 14:21:00,Stray,Normal,18 years,Spayed,2015-09-07 11:40:00,Return to Owner,18 years,Spayed,0 days 21:19:00
12,A769764,none,10/10/2017,Female,White,Black,Yorkshire Terrier,Mix,7500 South Interstate 35,Austin,...,2018-04-09 19:03:00,Stray,Normal,5 months,Intact,2018-04-13 16:12:00,Transfer,6 months,Spayed,3 days 21:09:00
13,A682230,none,12/25/2013,Female,White,none,Maltese,Mix,3737 Keats Dr,Austin,...,2014-06-25 16:27:00,Stray,Normal,5 months,Intact,2014-06-29 17:26:00,Transfer,6 months,Spayed,4 days 00:59:00
14,A749436,none,12/15/2016,Male,Brown,White,Dachshund,Mix,East Pleasant Valley And Stassney,Austin,...,2017-05-15 09:50:00,Stray,Normal,4 months,Intact,2017-05-15 13:25:00,Transfer,4 months,Intact,0 days 03:35:00

In [9]:
#Print column count and type
print(merged_df1.info())

#Export to csv
merged_df1.to_csv('AAC_In_Out_Final.csv', index= False)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 87855 entries, 0 to 90323
Data columns (total 21 columns):
Animal ID           87855 non-null object
Name                87855 non-null object
Date of Birth       87855 non-null object
Gender              87855 non-null object
Color1              87855 non-null object
Color2              87855 non-null object
Breed1              87855 non-null object
Breed2              87855 non-null object
Found Street        87855 non-null object
Found City          87855 non-null object
Found State         87855 non-null object
Intake_Date         87855 non-null datetime64[ns]
Intake Type         87855 non-null object
Intake Condition    87855 non-null object
Age upon Intake     87855 non-null object
Intake_Sex          87855 non-null object
Outcome_Date        87855 non-null datetime64[ns]
Outcome Type        87855 non-null object
Age upon Outcome    87855 non-null object
Outcome_Sex         87855 non-null object
AAC_Duration        87855 non-null timedelta64[ns]
dtypes: datetime64[ns](2), object(18), timedelta64[ns](1)
memory usage: 14.7+ MB
None

# LOAD

In [10]:
#load to SQL