In [94]:
import pandas as pd
import numpy as np
from datetime import datetime as dt
from datetime import timedelta as td

In [95]:
df = pd.read_csv("./Data/AAC_In_Out_Final.csv")
df.head()
#list(df.columns)
#print(df.dtypes)
#df.Breed2.unique()

,Animal ID,Name,Date of Birth,Gender,Color1,Color2,Breed1,Breed2,Found Street,Found City,...,Intake Type,Intake Condition,Age upon Intake,Intake_Sex,Outcome_Date,Outcome Type,Age upon Outcome,Outcome_Age_Months,Outcome_Sex,AAC_Duration
0,A006100,Scamp,2007-07-09 00:00:00,Male,Yellow,White,Spinone Italiano,Mix,2501 Magin Meadow Dr,Austin,...,Public Assist,Normal,6 years,Neutered,2014-03-08 17:10:00,Return to Owner,6 years,80,Neutered,1 days 02:44:00.000000000
1,A006100,Scamp,2007-07-09 00:00:00,Male,Yellow,White,Spinone Italiano,Mix,9409 Bluegrass Dr,Austin,...,Stray,Normal,10 years,Neutered,2017-12-07 00:00:00,Return to Owner,10 years,125,Neutered,-1 days +09:53:00.000000000
2,A006100,Scamp,2007-07-09 00:00:00,Male,Yellow,White,Spinone Italiano,Mix,2818 Palomino Trail,Austin,...,Public Assist,Normal,7 years,Neutered,2014-12-20 16:35:00,Return to Owner,7 years,89,Neutered,1 days 06:14:00.000000000
3,A047759,Oreo,2004-04-02 00:00:00,Male,Tricolor,none,Dachshund,none,800 Grove Blvd,Austin,...,Owner Surrender,Normal,10 years,Neutered,2014-04-07 15:12:00,Transfer,10 years,120,Neutered,4 days 23:17:00.000000000
4,A134067,Bandit,1997-10-16 00:00:00,Male,Brown,White,Shetland Sheepdog,none,none,Austin,...,Public Assist,Injured,16 years,Neutered,2013-11-16 11:54:00,Return to Owner,16 years,193,Neutered,0 days 02:52:00.000000000

In [96]:
# drop unecessary columns
dog_df1 = df[["Gender", "Color1", "Color2", "Breed1", "Breed2", "Intake_Date", "Intake Type", "Intake Condition", "Intake_Sex", "Outcome_Date", "Outcome Type", "Outcome_Age_Months", "Outcome_Sex", "AAC_Duration"]]
dog_df1.head()

,Gender,Color1,Color2,Breed1,Breed2,Intake_Date,Intake Type,Intake Condition,Intake_Sex,Outcome_Date,Outcome Type,Outcome_Age_Months,Outcome_Sex,AAC_Duration
0,Male,Yellow,White,Spinone Italiano,Mix,2014-03-07 14:26:00,Public Assist,Normal,Neutered,2014-03-08 17:10:00,Return to Owner,80,Neutered,1 days 02:44:00.000000000
1,Male,Yellow,White,Spinone Italiano,Mix,2017-12-07 14:07:00,Stray,Normal,Neutered,2017-12-07 00:00:00,Return to Owner,125,Neutered,-1 days +09:53:00.000000000
2,Male,Yellow,White,Spinone Italiano,Mix,2014-12-19 10:21:00,Public Assist,Normal,Neutered,2014-12-20 16:35:00,Return to Owner,89,Neutered,1 days 06:14:00.000000000
3,Male,Tricolor,none,Dachshund,none,2014-04-02 15:55:00,Owner Surrender,Normal,Neutered,2014-04-07 15:12:00,Transfer,120,Neutered,4 days 23:17:00.000000000
4,Male,Brown,White,Shetland Sheepdog,none,2013-11-16 09:02:00,Public Assist,Injured,Neutered,2013-11-16 11:54:00,Return to Owner,193,Neutered,0 days 02:52:00.000000000

In [97]:
# Get min and max of Outcome_Age_Months column
dog_df1["Outcome_Age_Months"].max()
dog_df1["Outcome_Age_Months"].min()

# Drop AAC_Duration, and Outcome_Age_Months rows with negative values
dog_df2 = dog_df1[dog_df1["Outcome_Age_Months"] >=0]

In [98]:
#convert Outcome date column to month
type(dog_df2.Outcome_Date[0])
dog_df2.Outcome_Date = pd.to_datetime(dog_df2.Outcome_Date)
dog_df2['Outcome_Date_Month'] = dog_df2.Outcome_Date.dt.month

#print result
dog_df2.head()

/Users/suprajasharma/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

,Gender,Color1,Color2,Breed1,Breed2,Intake_Date,Intake Type,Intake Condition,Intake_Sex,Outcome_Date,Outcome Type,Outcome_Age_Months,Outcome_Sex,AAC_Duration,Outcome_Date_Month
0,Male,Yellow,White,Spinone Italiano,Mix,2014-03-07 14:26:00,Public Assist,Normal,Neutered,2014-03-08 17:10:00,Return to Owner,80,Neutered,1 days 02:44:00.000000000,3
1,Male,Yellow,White,Spinone Italiano,Mix,2017-12-07 14:07:00,Stray,Normal,Neutered,2017-12-07 00:00:00,Return to Owner,125,Neutered,-1 days +09:53:00.000000000,12
2,Male,Yellow,White,Spinone Italiano,Mix,2014-12-19 10:21:00,Public Assist,Normal,Neutered,2014-12-20 16:35:00,Return to Owner,89,Neutered,1 days 06:14:00.000000000,12
3,Male,Tricolor,none,Dachshund,none,2014-04-02 15:55:00,Owner Surrender,Normal,Neutered,2014-04-07 15:12:00,Transfer,120,Neutered,4 days 23:17:00.000000000,4
4,Male,Brown,White,Shetland Sheepdog,none,2013-11-16 09:02:00,Public Assist,Injured,Neutered,2013-11-16 11:54:00,Return to Owner,193,Neutered,0 days 02:52:00.000000000,11

In [99]:
def td_cleaner2(timed):
    seconds = timed.total_seconds()
    return(seconds)

In [100]:
#convert Intake date column to month
type(dog_df2.Intake_Date[0])
dog_df2.Intake_Date = pd.to_datetime(dog_df2.Intake_Date)
dog_df2['Intake_Date_Month'] = dog_df2.Intake_Date.dt.month

dog_df2.head()

/Users/suprajasharma/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

,Gender,Color1,Color2,Breed1,Breed2,Intake_Date,Intake Type,Intake Condition,Intake_Sex,Outcome_Date,Outcome Type,Outcome_Age_Months,Outcome_Sex,AAC_Duration,Outcome_Date_Month,Intake_Date_Month
0,Male,Yellow,White,Spinone Italiano,Mix,2014-03-07 14:26:00,Public Assist,Normal,Neutered,2014-03-08 17:10:00,Return to Owner,80,Neutered,1 days 02:44:00.000000000,3,3
1,Male,Yellow,White,Spinone Italiano,Mix,2017-12-07 14:07:00,Stray,Normal,Neutered,2017-12-07 00:00:00,Return to Owner,125,Neutered,-1 days +09:53:00.000000000,12,12
2,Male,Yellow,White,Spinone Italiano,Mix,2014-12-19 10:21:00,Public Assist,Normal,Neutered,2014-12-20 16:35:00,Return to Owner,89,Neutered,1 days 06:14:00.000000000,12,12
3,Male,Tricolor,none,Dachshund,none,2014-04-02 15:55:00,Owner Surrender,Normal,Neutered,2014-04-07 15:12:00,Transfer,120,Neutered,4 days 23:17:00.000000000,4,4
4,Male,Brown,White,Shetland Sheepdog,none,2013-11-16 09:02:00,Public Assist,Injured,Neutered,2013-11-16 11:54:00,Return to Owner,193,Neutered,0 days 02:52:00.000000000,11,11

In [101]:


dog_df2["AAC_Duration_Clean"] = pd.to_timedelta(dog_df2["AAC_Duration"])

/Users/suprajasharma/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [102]:
dog_df2["TDSeconds"] = dog_df2.AAC_Duration_Clean.apply(td_cleaner2)

/Users/suprajasharma/anaconda3/envs/PythonData/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [103]:
dog_df2["TDSeconds"]

dog_df2 = dog_df2[dog_df2["TDSeconds"] >=0]

dog_df2

,Gender,Color1,Color2,Breed1,Breed2,Intake_Date,Intake Type,Intake Condition,Intake_Sex,Outcome_Date,Outcome Type,Outcome_Age_Months,Outcome_Sex,AAC_Duration,Outcome_Date_Month,Intake_Date_Month,AAC_Duration_Clean,TDSeconds
0,Male,Yellow,White,Spinone Italiano,Mix,2014-03-07 14:26:00,Public Assist,Normal,Neutered,2014-03-08 17:10:00,Return to Owner,80,Neutered,1 days 02:44:00.000000000,3,3,1 days 02:44:00,96240.0
2,Male,Yellow,White,Spinone Italiano,Mix,2014-12-19 10:21:00,Public Assist,Normal,Neutered,2014-12-20 16:35:00,Return to Owner,89,Neutered,1 days 06:14:00.000000000,12,12,1 days 06:14:00,108840.0
3,Male,Tricolor,none,Dachshund,none,2014-04-02 15:55:00,Owner Surrender,Normal,Neutered,2014-04-07 15:12:00,Transfer,120,Neutered,4 days 23:17:00.000000000,4,4,4 days 23:17:00,429420.0
4,Male,Brown,White,Shetland Sheepdog,none,2013-11-16 09:02:00,Public Assist,Injured,Neutered,2013-11-16 11:54:00,Return to Owner,193,Neutered,0 days 02:52:00.000000000,11,11,0 days 02:52:00,10320.0
5,Female,Black,White,Labrador Retriever,Pit Bull,2013-11-16 14:46:00,Stray,Aged,Spayed,2013-11-17 11:40:00,Return to Owner,185,Spayed,0 days 20:54:00.000000000,11,11,0 days 20:54:00,75240.0
6,Female,Black,Gray,Miniature Schnauzer,Mix,2014-11-14 15:11:00,Stray,Normal,Intact,2014-11-14 19:28:00,Return to Owner,181,Intact,0 days 04:17:00.000000000,11,11,0 days 04:17:00,15420.0
7,Male,Brown,White,Lhasa Apso,Mix,2014-09-15 11:28:00,Stray,Normal,Neutered,2014-09-15 16:35:00,Return to Owner,181,Neutered,0 days 05:07:00.000000000,9,9,0 days 05:07:00,18420.0
8,Male,White,Black,Shetland Sheepdog,Mix,2014-03-17 09:45:00,Public Assist,Normal,Neutered,2014-03-23 15:57:00,Return to Owner,180,Neutered,6 days 06:12:00.000000000,3,3,6 days 06:12:00,540720.0
9,Female,Brown,White,Shetland Sheepdog,Mix,2015-09-18 17:46:00,Stray,Normal,Spayed,2015-09-18 19:04:00,Return to Owner,217,Spayed,0 days 01:18:00.000000000,9,9,0 days 01:18:00,4680.0
10,Male,Black,Tan,Dachshund,Mix,2013-10-03 15:47:00,Owner Surrender,Normal,Neutered,2013-11-22 09:44:00,Adoption,193,Neutered,49 days 17:57:00.000000000,11,10,49 days 17:57:00,4298220.0
11,Male,Black,White,Border Collie,Mix,2015-02-17 13:17:00,Owner Surrender,Sick,Neutered,2015-02-17 16:25:00,Euthanasia,178,Neutered,0 days 03:08:00.000000000,2,2,0 days 03:08:00,11280.0
12,Male,Tan,Black,Chihuahua Shorthair,none,2016-09-28 12:05:00,Public Assist,Aged,Neutered,2016-10-07 12:34:00,Adoption,208,Neutered,9 days 00:29:00.000000000,10,9,9 days 00:29:00,779340.0
13,Female,Tan,Black,German Shepherd,Labrador Retriever,2013-11-25 17:18:00,Stray,Normal,Intact,2013-12-06 14:34:00,Return to Owner,165,Intact,10 days 21:16:00.000000000,12,11,10 days 21:16:00,940560.0
14,Male,Black,none,Newfoundland,Mix,2014-08-04 13:51:00,Stray,Normal,Neutered,2014-08-04 16:31:00,Return to Owner,163,Neutered,0 days 02:40:00.000000000,8,8,0 days 02:40:00,9600.0
15,Male,Gold,Gold,Pug,none,2013-12-02 15:33:00,Owner Surrender,Sick,Neutered,2013-12-02 17:09:00,Euthanasia,182,Neutered,0 days 01:36:00.000000000,12,12,0 days 01:36:00,5760.0
16,Male,Gold,Gold,Pug,none,2013-12-02 15:33:00,Owner Surrender,Sick,Neutered,2013-12-02 17:11:00,Euthanasia,182,Neutered,0 days 01:38:00.000000000,12,12,0 days 01:38:00,5880.0
17,Female,Brown,White,Staffordshire,Mix,2015-04-28 15:08:00,Stray,Injured,Spayed,2015-04-29 13:42:00,Euthanasia,191,Spayed,0 days 22:34:00.000000000,4,4,0 days 22:34:00,81240.0
18,Male,Brown,White,Labrador Retriever,Mix,2013-10-27 11:17:00,Stray,Normal,Neutered,2013-10-28 12:37:00,Return to Owner,155,Neutered,1 days 01:20:00.000000000,10,10,1 days 01:20:00,91200.0
19,Male,Sable,White,Labrador Retriever,Beagle,2015-10-06 12:29:00,Stray,Normal,Neutered,2015-10-29 15:00:00,Adoption,184,Neutered,23 days 02:31:00.000000000,10,10,23 days 02:31:00,1996260.0
20,Female,Blue Merle,Tan,Catahoula,Labrador Retriever,2013-11-09 17:00:00,Stray,Normal,Spayed,2013-11-09 17:42:00,Return to Owner,151,Spayed,0 days 00:42:00.000000000,11,11,0 days 00:42:00,2520.0
21,Male,Blue Merle,none,Queensland Heeler,none,2015-03-13 15:20:00,Euthanasia Request,Aged,Intact,2015-03-13 17:01:00,Euthanasia,168,Intact,0 days 01:41:00.000000000,3,3,0 days 01:41:00,6060.0
22,Male,Brown,Black,Rottweiler,Chow Chow,2014-09-06 14:37:00,Stray,Aged,Neutered,2014-09-06 18:52:00,Return to Owner,159,Neutered,0 days 04:15:00.000000000,9,9,0 days 04:15:00,15300.0
23,Male,Black,Tricolor,Smooth Fox Terrier,Mix,2014-07-05 07:13:00,Stray,Normal,Neutered,2014-07-09 12:00:00,Return to Owner,156,Neutered,4 days 04:47:00.000000000,7,7,4 days 04:47:00,362820.0
24,Male,Gray,White,Rat Terrier,Mix,2016-06-09 16:22:00,Stray,Normal,Neutered,2016-06-17 12:37:00,Transfer,181,Neutered,7 days 20:15:00.000000000,6,6,7 days 20:15:00,677700.0
25,Male,Tan,none,Labrador Retriever,Mix,2015-05-20 22:34:00,Stray,Normal,Neutered,2015-05-25 11:49:00,Transfer,180,Neutered,4 days 13:15:00.000000000,5,5,4 days 13:15:00,393300.0
26,Male,Tan,none,Labrador Retriever,Mix,2014-07-03 17:55:00,Stray,Normal,Neutered,2014-07-04 15:26:00,Return to Owner,170,Neutered,0 days 21:31:00.000000000,7,7,0 days 21:31:00,77460.0
27,Female,Black,Brown,German Shepherd,Mix,2016-08-17 14:05:00,Stray,Normal,Spayed,2016-11-15 10:37:00,Adoption,190,Spayed,89 days 20:32:00.000000000,11,8,89 days 20:32:00,7763520.0
28,Female,Tricolor,none,Border Collie,none,2016-03-02 11:55:00,Euthanasia Request,Aged,Spayed,2016-03-02 13:16:00,Euthanasia,171,Spayed,0 days 01:21:00.000000000,3,3,0 days 01:21:00,4860.0
29,Male,Cream,none,German Shepherd,Mix,2014-09-04 15:16:00,Stray,Normal,Neutered,2014-09-04 16:12:00,Return to Owner,155,Neutered,0 days 00:56:00.000000000,9,9,0 days 00:56:00,3360.0
30,Female,Tan,none,Chihuahua Shorthair,Mix,2017-10-22 18:41:00,Stray,Normal,Spayed,2017-10-23 11:32:00,Return to Owner,225,Spayed,0 days 16:51:00.000000000,10,10,0 days 16:51:00,60660.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60810,Male,Brown Brindle,White,Boston Terrier,none,2019-10-31 18:38:00,Stray,Normal,Intact,2019-11-05 15:05:00,Return to Owner,61,Intact,4 days 20:27:00.000000000,11,10,4 days 20:27:00,419220.0
60811,Male,White,Black,Pit Bull,none,2019-10-31 18:47:00,Stray,Normal,Neutered,2019-11-03 14:10:00,Return to Owner,97,Neutered,2 days 19:23:00.000000000,11,10,2 days 19:23:00,242580.0
60812,Female,Black,White,Shih Tzu,none,2019-10-31 19:03:00,Stray,Normal,Intact,2019-11-04 13:01:00,Transfer,25,Intact,3 days 17:58:00.000000000,11,10,3 days 17:58:00,323880.0
60813,Female,Cream,none,Miniature Poodle,Bichon Frise,2019-10-31 19:03:00,Stray,Normal,Intact,2019-11-04 17:23:00,Adoption,25,Spayed,3 days 22:20:00.000000000,11,10,3 days 22:20:00,339600.0
60814,Female,Black,White,Chihuahua Shorthair,none,2019-11-01 11:15:00,Stray,Normal,Intact,2019-11-05 10:48:00,Adoption,24,Spayed,3 days 23:33:00.000000000,11,11,3 days 23:33:00,343980.0
60815,Male,White,Black,Dachshund,none,2019-11-01 12:33:00,Stray,Normal,Intact,2019-11-05 14:19:00,Transfer,6,Intact,4 days 01:46:00.000000000,11,11,4 days 01:46:00,351960.0
60816,Male,Blue,White,Pit Bull,none,2019-11-01 12:43:00,Stray,Normal,Intact,2019-11-02 17:58:00,Return to Owner,4,Intact,1 days 05:15:00.000000000,11,11,1 days 05:15:00,105300.0
60817,Female,Black,White,Border Collie,Mix,2019-11-01 15:11:00,Owner Surrender,Normal,Spayed,2019-11-02 19:15:00,Adoption,24,Spayed,1 days 04:04:00.000000000,11,11,1 days 04:04:00,101040.0
60818,Male,Brown,Tricolor,Black Mouth Cur,Mix,2019-11-01 15:01:00,Owner Surrender,Normal,Intact,2019-11-04 18:41:00,Adoption,3,Neutered,3 days 03:40:00.000000000,11,11,3 days 03:40:00,272400.0
60819,Male,Red,none,Vizsla,none,2019-11-01 14:57:00,Stray,Normal,Neutered,2019-11-02 18:12:00,Return to Owner,24,Neutered,1 days 03:15:00.000000000,11,11,1 days 03:15:00,98100.0
60820,Male,Black,Tan,Chihuahua Shorthair,none,2019-11-01 15:25:00,Stray,Normal,Intact,2019-11-04 12:10:00,Return to Owner,84,Intact,2 days 20:45:00.000000000,11,11,2 days 20:45:00,247500.0
60821,Male,Black,White,Siberian Husky,none,2019-11-01 15:53:00,Stray,Normal,Neutered,2019-11-05 12:56:00,Adoption,12,Neutered,3 days 21:03:00.000000000,11,11,3 days 21:03:00,334980.0
60822,Female,Tan,Tricolor,Miniature Poodle,Mix,2019-11-01 15:59:00,Owner Surrender,Normal,Intact,2019-11-04 18:16:00,Adoption,2,Spayed,3 days 02:17:00.000000000,11,11,3 days 02:17:00,267420.0
60823,Female,Brown,none,Irish Setter,none,2019-11-02 10:26:00,Stray,Normal,Spayed,2019-11-02 18:11:00,Return to Owner,156,Spayed,0 days 07:45:00.000000000,11,11,0 days 07:45:00,27900.0
60824,Male,Cream,Tan,Shih Tzu,none,2019-11-02 11:06:00,Owner Surrender,Normal,Intact,2019-11-04 13:01:00,Transfer,36,Intact,2 days 01:55:00.000000000,11,11,2 days 01:55:00,179700.0
60825,Female,White,Tan,Labrador Retriever,Mix,2019-11-02 11:13:00,Owner Surrender,Normal,Intact,2019-11-05 13:32:00,Transfer,11,Intact,3 days 02:19:00.000000000,11,11,3 days 02:19:00,267540.0
60826,Female,Black,White,Labrador Retriever,Mix,2019-11-02 11:13:00,Owner Surrender,Normal,Intact,2019-11-05 13:31:00,Transfer,11,Intact,3 days 02:18:00.000000000,11,11,3 days 02:18:00,267480.0
60827,Female,Black,White,Labrador Retriever,Mix,2019-11-02 11:13:00,Owner Surrender,Normal,Intact,2019-11-05 13:31:00,Transfer,11,Intact,3 days 02:18:00.000000000,11,11,3 days 02:18:00,267480.0
60828,Female,Tan,none,Chihuahua Shorthair,none,2019-11-02 16:01:00,Owner Surrender,Normal,Intact,2019-11-05 17:05:00,Adoption,12,Spayed,3 days 01:04:00.000000000,11,11,3 days 01:04:00,263040.0
60829,Female,Black,none,Labrador Retriever,none,2019-11-02 18:38:00,Stray,Normal,Spayed,2019-11-03 13:07:00,Return to Owner,72,Spayed,0 days 18:29:00.000000000,11,11,0 days 18:29:00,66540.0
60830,Male,Tan,White,Labrador Retriever,none,2019-11-02 18:38:00,Stray,Normal,Neutered,2019-11-03 13:07:00,Return to Owner,96,Neutered,0 days 18:29:00.000000000,11,11,0 days 18:29:00,66540.0
60831,Female,Brown,White,American Pit Bull Terrier,none,2019-11-02 23:50:00,Stray,Normal,Spayed,2019-11-05 12:05:00,Return to Owner,24,Spayed,2 days 12:15:00.000000000,11,11,2 days 12:15:00,216900.0
60832,Female,Chocolate,none,Labrador Retriever,Standard Poodle,2019-11-03 02:15:00,Stray,Normal,Spayed,2019-11-03 13:06:00,Return to Owner,72,Spayed,0 days 10:51:00.000000000,11,11,0 days 10:51:00,39060.0
60833,Male,Black,White,Border Collie,Mix,2019-11-03 08:47:00,Stray,Injured,Neutered,2019-11-03 12:49:00,Return to Owner,137,Neutered,0 days 04:02:00.000000000,11,11,0 days 04:02:00,14520.0
60834,Male,Yellow,none,Labrador Retriever,none,2019-11-03 11:47:00,Stray,Normal,Neutered,2019-11-03 13:09:00,Return to Owner,132,Neutered,0 days 01:22:00.000000000,11,11,0 days 01:22:00,4920.0
60835,Male,Black,Brown,Miniature Pinscher,Mix,2019-11-03 13:11:00,Owner Surrender,Normal,Intact,2019-11-04 00:00:00,Adoption,3,Intact,0 days 10:49:00.000000000,11,11,0 days 10:49:00,38940.0
60836,Male,Chocolate,White,Labrador Retriever,Mix,2019-11-03 15:49:00,Stray,Normal,Intact,2019-11-03 16:29:00,Return to Owner,3,Intact,0 days 00:40:00.000000000,11,11,0 days 00:40:00,2400.0
60837,Female,Chocolate,White,Australian Kelpie,Mix,2019-11-04 15:38:00,Stray,Normal,Intact,2019-11-04 19:10:00,Return to Owner,24,Intact,0 days 03:32:00.000000000,11,11,0 days 03:32:00,12720.0
60838,Male,Red,White,Chihuahua Shorthair,none,2019-11-04 16:48:00,Stray,Normal,Neutered,2019-11-05 14:42:00,Return to Owner,48,Neutered,0 days 21:54:00.000000000,11,11,0 days 21:54:00,78840.0
60839,Female,White,Blue,Pit Bull,none,2019-11-05 11:08:00,Stray,Injured,Intact,2019-11-05 15:29:00,Transfer,12,Intact,0 days 04:21:00.000000000,11,11,0 days 04:21:00,15660.0

In [104]:
dog_df2["TDSeconds"] = pd.to_numeric(dog_df2.TDSeconds)


dog_df2["TDDays"] = dog_df2["TDSeconds"]/86400

dog_df2.head()

,Gender,Color1,Color2,Breed1,Breed2,Intake_Date,Intake Type,Intake Condition,Intake_Sex,Outcome_Date,Outcome Type,Outcome_Age_Months,Outcome_Sex,AAC_Duration,Outcome_Date_Month,Intake_Date_Month,AAC_Duration_Clean,TDSeconds,TDDays
0,Male,Yellow,White,Spinone Italiano,Mix,2014-03-07 14:26:00,Public Assist,Normal,Neutered,2014-03-08 17:10:00,Return to Owner,80,Neutered,1 days 02:44:00.000000000,3,3,1 days 02:44:00,96240.0,1.113889
2,Male,Yellow,White,Spinone Italiano,Mix,2014-12-19 10:21:00,Public Assist,Normal,Neutered,2014-12-20 16:35:00,Return to Owner,89,Neutered,1 days 06:14:00.000000000,12,12,1 days 06:14:00,108840.0,1.259722
3,Male,Tricolor,none,Dachshund,none,2014-04-02 15:55:00,Owner Surrender,Normal,Neutered,2014-04-07 15:12:00,Transfer,120,Neutered,4 days 23:17:00.000000000,4,4,4 days 23:17:00,429420.0,4.970139
4,Male,Brown,White,Shetland Sheepdog,none,2013-11-16 09:02:00,Public Assist,Injured,Neutered,2013-11-16 11:54:00,Return to Owner,193,Neutered,0 days 02:52:00.000000000,11,11,0 days 02:52:00,10320.0,0.119444
5,Female,Black,White,Labrador Retriever,Pit Bull,2013-11-16 14:46:00,Stray,Aged,Spayed,2013-11-17 11:40:00,Return to Owner,185,Spayed,0 days 20:54:00.000000000,11,11,0 days 20:54:00,75240.0,0.870833

In [105]:
#convert Intake date column to month
type(dog_df2.Intake_Date[0])
dog_df2.Intake_Date = pd.to_datetime(dog_df2.Intake_Date)
dog_df2['Intake_Date_Month'] = dog_df2.Intake_Date.dt.month

dog_df2.head()

,Gender,Color1,Color2,Breed1,Breed2,Intake_Date,Intake Type,Intake Condition,Intake_Sex,Outcome_Date,Outcome Type,Outcome_Age_Months,Outcome_Sex,AAC_Duration,Outcome_Date_Month,Intake_Date_Month,AAC_Duration_Clean,TDSeconds,TDDays
0,Male,Yellow,White,Spinone Italiano,Mix,2014-03-07 14:26:00,Public Assist,Normal,Neutered,2014-03-08 17:10:00,Return to Owner,80,Neutered,1 days 02:44:00.000000000,3,3,1 days 02:44:00,96240.0,1.113889
2,Male,Yellow,White,Spinone Italiano,Mix,2014-12-19 10:21:00,Public Assist,Normal,Neutered,2014-12-20 16:35:00,Return to Owner,89,Neutered,1 days 06:14:00.000000000,12,12,1 days 06:14:00,108840.0,1.259722
3,Male,Tricolor,none,Dachshund,none,2014-04-02 15:55:00,Owner Surrender,Normal,Neutered,2014-04-07 15:12:00,Transfer,120,Neutered,4 days 23:17:00.000000000,4,4,4 days 23:17:00,429420.0,4.970139
4,Male,Brown,White,Shetland Sheepdog,none,2013-11-16 09:02:00,Public Assist,Injured,Neutered,2013-11-16 11:54:00,Return to Owner,193,Neutered,0 days 02:52:00.000000000,11,11,0 days 02:52:00,10320.0,0.119444
5,Female,Black,White,Labrador Retriever,Pit Bull,2013-11-16 14:46:00,Stray,Aged,Spayed,2013-11-17 11:40:00,Return to Owner,185,Spayed,0 days 20:54:00.000000000,11,11,0 days 20:54:00,75240.0,0.870833

In [106]:
#convert Outcome date column to month
type(dog_df2.Outcome_Date[0])
dog_df2.Outcome_Date = pd.to_datetime(dog_df2.Outcome_Date)
dog_df2['Outcome_Date_Month'] = dog_df2.Outcome_Date.dt.month

#print result
dog_df2.head()

,Gender,Color1,Color2,Breed1,Breed2,Intake_Date,Intake Type,Intake Condition,Intake_Sex,Outcome_Date,Outcome Type,Outcome_Age_Months,Outcome_Sex,AAC_Duration,Outcome_Date_Month,Intake_Date_Month,AAC_Duration_Clean,TDSeconds,TDDays
0,Male,Yellow,White,Spinone Italiano,Mix,2014-03-07 14:26:00,Public Assist,Normal,Neutered,2014-03-08 17:10:00,Return to Owner,80,Neutered,1 days 02:44:00.000000000,3,3,1 days 02:44:00,96240.0,1.113889
2,Male,Yellow,White,Spinone Italiano,Mix,2014-12-19 10:21:00,Public Assist,Normal,Neutered,2014-12-20 16:35:00,Return to Owner,89,Neutered,1 days 06:14:00.000000000,12,12,1 days 06:14:00,108840.0,1.259722
3,Male,Tricolor,none,Dachshund,none,2014-04-02 15:55:00,Owner Surrender,Normal,Neutered,2014-04-07 15:12:00,Transfer,120,Neutered,4 days 23:17:00.000000000,4,4,4 days 23:17:00,429420.0,4.970139
4,Male,Brown,White,Shetland Sheepdog,none,2013-11-16 09:02:00,Public Assist,Injured,Neutered,2013-11-16 11:54:00,Return to Owner,193,Neutered,0 days 02:52:00.000000000,11,11,0 days 02:52:00,10320.0,0.119444
5,Female,Black,White,Labrador Retriever,Pit Bull,2013-11-16 14:46:00,Stray,Aged,Spayed,2013-11-17 11:40:00,Return to Owner,185,Spayed,0 days 20:54:00.000000000,11,11,0 days 20:54:00,75240.0,0.870833

In [107]:
dog_df2 = dog_df2.loc[:,~dog_df2.columns.duplicated()]


dog_cleandf = dog_df2[['Gender', 'Color1', 'Color2', 'Breed1', 'Breed2', 'Intake Type', 'Intake Condition', 'Intake_Sex', 'Outcome Type', 'Outcome_Age_Months', 'Outcome_Sex', 'Outcome_Date_Month', 'Intake_Date_Month', 'TDDays']]
dog_cleandf.head()

,Gender,Color1,Color2,Breed1,Breed2,Intake Type,Intake Condition,Intake_Sex,Outcome Type,Outcome_Age_Months,Outcome_Sex,Outcome_Date_Month,Intake_Date_Month,TDDays
0,Male,Yellow,White,Spinone Italiano,Mix,Public Assist,Normal,Neutered,Return to Owner,80,Neutered,3,3,1.113889
2,Male,Yellow,White,Spinone Italiano,Mix,Public Assist,Normal,Neutered,Return to Owner,89,Neutered,12,12,1.259722
3,Male,Tricolor,none,Dachshund,none,Owner Surrender,Normal,Neutered,Transfer,120,Neutered,4,4,4.970139
4,Male,Brown,White,Shetland Sheepdog,none,Public Assist,Injured,Neutered,Return to Owner,193,Neutered,11,11,0.119444
5,Female,Black,White,Labrador Retriever,Pit Bull,Stray,Aged,Spayed,Return to Owner,185,Spayed,11,11,0.870833

In [110]:
dog_cleandf.columns = ['Gender', 'Color1', 'Color2', 'Breed1', 'Breed2', 'Intake_Type', 'Intake_Condition', 'Intake_Sex', 'Outcome_Type', 'Outcome_Age_Month', 'Outcome_Sex', 'Outcome_Date_Month', 'Intake_Date_Month', 'Duration_Day']

dog_cleandf.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 59601 entries, 0 to 60839
Data columns (total 14 columns):
Gender                59601 non-null object
Color1                59601 non-null object
Color2                59601 non-null object
Breed1                59601 non-null object
Breed2                59601 non-null object
Intake_Type           59601 non-null object
Intake_Condition      59601 non-null object
Intake_Sex            59601 non-null object
Outcome_Type          59601 non-null object
Outcome_Age_Month     59601 non-null int64
Outcome_Sex           59601 non-null object
Outcome_Date_Month    59601 non-null int64
Intake_Date_Month     59601 non-null int64
Duration_Day          59601 non-null float64
dtypes: float64(1), int64(3), object(10)
memory usage: 9.3+ MB

In [111]:
dog_cleandf.to_csv('MachineLearning.csv', index=False)